require 'rugged'
require 'logger'
require 'pp'

require 'git-merge/version'
require 'git-merge/logger'
require 'git-merge/error'
require 'git-merge/block'
require 'git-merge/merge'
require 'git-merge/repo'
